process.env.REACT_APP_FIRESTORE_API_KEY = "AIzaSyBVYdj70Ng90OUqIsgKB7JNaPKpPLkv36s";
process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "40055008685";
process.env.REACT_APP_MAPBOX_API_KEY = 'pk.eyJ1IjoiaG9yc2VleWVwaGlsIiwiYSI6ImNqZDF3ZHptaTI0OHkyeG4ydTM2cWdhNmIifQ.vvmBOCZBWKb3rKghrQwVlw';

process.env.FIRESTORE_API_KEY = "AIzaSyBVYdj70Ng90OUqIsgKB7JNaPKpPLkv36s";
process.env.FIREBASE_MESSAGING_SENDER_ID = "40055008685";
process.env.MAPBOX_API_KEY = 'pk.eyJ1IjoiaG9yc2VleWVwaGlsIiwiYSI6ImNqZDF3ZHptaTI0OHkyeG4ydTM2cWdhNmIifQ.vvmBOCZBWKb3rKghrQwVlw';
